require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.theme")

require("user.lsp")

require("user.alpha-dash")
require("user.autocommands")
require("user.diagnostic")
require("user.harpoon")
require("user.telescope")
require("user.tree")
require("user.treesitter")
require("user.which-key")
